### ISSUE TITLE
Create global scss class to keep constant width in all components

### ISSUE THREAD

**Issue by OtisRed** [CodeForPoznan/codeforpoznan.pl_v3#107]

**Comment by OtisRed** [comment]
@Loczi94 do you want it?

**Comment by Loczi94** [comment]
I need more detailed explanation.

**Comment by OtisRed** [comment]
If you take a look at the webpage blue containers have bigger width than white ones. The task is about creating te global class that could be used in all containers to keep the same width across the whole page.

**Comment by OtisRed** [comment]
explained in #154
