### ISSUE TITLE
Use Python http.HTTPStatus instead of magic numbers

### ISSUE THREAD

**Issue by magul** [CodeForPoznan/codeforpoznan.pl_v3#131]
In code we have a lot of responses with `magic number` provided as second element of tuple, for example:
```
            return {"message": err.messages}, 400
```
That's a bad habit, we should instead use something that will clarify what this `400` means.

To do so we should use Python standard library `http.HTTPStatus` (see: https://docs.python.org/3/library/http.html#http.HTTPStatus) so that line will looks like
```
            return {"message": err.messages}, HTTPStatus.BAD_REQUEST
```

**Comment by OtisRed** [comment]
@wrozda

**Comment by w1stler** [comment]
I think this one is already resolved. @wrozda ?

**Comment by wrozda** [comment]
@w1stler Yes it's done. I'm not quite sure how to test it.

**Comment by magul** [comment]
Done in #140
