### ISSUE TITLE
Unique constraint on participant

### ISSUE THREAD

**Issue by w1stler** [CodeForPoznan/codeforpoznan.pl_v3#153]
As discussed in #125, we need to change schema for participant. Currently there is only one field required (name), which is not unique thus we can't check if particular user already exists when creating one. We should add unique constraint to one of the fields and check this while creating new participant.

AC1. Add unique constraint to participant - suggestion to go with email
AC2. Add validation in endpoint

**Comment by w1stler** [comment]
- verify other models

**Comment by kristhina** [comment]
@w1stler remember also about the participant name - the limit should be 2 or 3 (not 5), because of all "Jan", "Ewa" etc.
