### ISSUE TITLE
Fix test of participant details

### ISSUE THREAD

**Issue by ngiersz** [CodeForPoznan/codeforpoznan.pl_v3#165]
File test_participant_details imports non existing participant_schema.

**Comment by magul** [comment]
Can you confirm @ngiersz that this issue was resolved in #114? It introduces different issue (see #175) but this error causing import was changed there.

**Comment by moniabak** [comment]
I check changes from #114 and they are on master expect folder blueprint. I ran test_participant_details and there was no import problem. I saw too in #114 that there was changed import in test_participant_details.py which could cause this bug.

**Comment by OtisRed** [comment]
Then I'm closing. Thanks!
