### ISSUE TITLE
Cleanup in login endpoint

### ISSUE THREAD

**Issue by stanislawK** [CodeForPoznan/codeforpoznan.pl_v3#201]
Login serializer validates input data, and both username and password are required fields.
In login endpoint we catch validation errors if appears:
        schema = LoginSchema() 

        try: 

            result = schema.load(request.json) 

        except ValidationError as error: 

            return {"msg": "Wrong input data", 

                    "errors": error.messages}, HTTPStatus.BAD_REQUEST 

Then i think is no reason to keep also few lines down:
        if not (username and password): 

            return {"msg": "Username and password required"}, 

            HTTPStatus.BAD_REQUEST 

If one of field is missing, validation error from marshallow should be raised,  which was tested in pr #200 in test_login_with_one_value_missing.

**Comment by moniabak** [comment]
Hi Can I take that one as a starter?

**Comment by w1stler** [comment]
Go for it! 🐯

**Comment by moniabak** [comment]
Changes in https://github.com/CodeForPoznan/codeforpoznan.pl_v3/pull/218.
What now with this one?

**Comment by magul** [comment]
Can someone confirm that it was resolved? I've just seen #218 which deletes these 3 lines, but at the same time, I see  #184 which re-introduces it. There were even a bug in how this tuple was written, which I've resolved in #240.

**Comment by MargoWM** [comment]
@halsing

**Comment by OtisRed** [comment]
@stanislawK I remeber you talking about it in the context of some PR that you wouldn't want to merge - can you look at it and say if this task is valid?

**Comment by stanislawK** [comment]
Task is valid. [That change](https://github.com/CodeForPoznan/codeforpoznan.pl_v3/commit/ca7e39307e1112166148c3e519d4f573ee91fad1#diff-ad6459b9a428cecccc788192766f1baa29be2834b7f1cd752e20c20ba4d07400) was valid, and there might be something more to trim. Inside endpoint we don't want to have have checks which have been already done by marshmallow during the serialization.
