### ISSUE TITLE
Change string formatting

### ISSUE THREAD

**Issue by stanislawK** [CodeForPoznan/codeforpoznan.pl_v3#204]
After python upgrade (pr #187) we could change string formatting from str.format() to f-strings.

**Comment by udaykiranreddykondreddy** [comment]
@stanislawK Can I work on this?

**Comment by magul** [comment]
You can certainly work on that @udaykiranreddykondreddy but be aware that's waiting for #187 to be merged and probably you will encounter an enormous number of merge conflicts if you will start working on whatever is right now in `master` branch.

**Comment by udaykiranreddykondreddy** [comment]
@magul Then I will wait until #187 get merged

**Comment by OtisRed** [comment]
@udaykiranreddykondreddy #187 has been marged - do you want to work on this?

**Comment by udaykiranreddykondreddy** [comment]
@OtisRed Yes, I will work on this.

**Comment by OtisRed** [comment]
@udaykiranreddykondreddy do you currently work on this?

**Comment by halsing** [comment]
I will do this.

**Comment by halsing** [comment]
link to the solution :
https://github.com/halsing/codeforpoznan.pl_v3

**Comment by OtisRed** [comment]
Go to the original code for poznań repo and click "create pull request" then find option "compare across forks" and pick codeforpoznan_v3 master as "base" and your branch as "head". 

We laso have the convention to describe:
1) Change string formatting (fixes #204) in the title 
2) Describe briefly what has been done
3) Explain shortly how another person should test it to make sure that it works properly
