### ISSUE TITLE
Py-test infrastructure

### ISSUE THREAD

**Issue by OtisRed** [CodeForPoznan/codeforpoznan.pl_v3#21]
@stanislawK discovered that there are some problems with writing tests that are related to the organization of files in backend folder - apparently there is some issue with "circular imports". We need to solve this in order to be able to write tests that work. 

### Until now there were two voices on the matter:
* Staszek suggested we might have to reorganize the structure of files 
* Jacek suggested that we need "factory" - he might have been thinking about [this](http://flask.pocoo.org/docs/1.0/patterns/appfactories/)?

**Comment by stanislawK** [comment]
I think that we should create app factory (like in docks which you mentioned). Probably also setup.py like [there](http://flask.pocoo.org/docs/1.0/patterns/packages/). It requires different app's structure. I'm trying figure it out. We need something like that, more or less:
```

└── backend
    ├── api
    │   ├── config.py
    │   ├── __init__.py
    │   ├── mail.py
    │   ├── manage.py
    │   ├── migrations
    │   │   ├── ...
    │   ├── models.py
    │   ├── serializers
    │   │   ├── ...
    │   └── views.py
    ├── Dockerfile
    ├── setup.py
    └── tests
        ├── ...
```
