### ISSUE TITLE
Create vuetify theme for buttons

### ISSUE THREAD

**Issue by OtisRed** [CodeForPoznan/codeforpoznan.pl_v3#213]
Look n the comment - the problem is that we want to have our own blue to color different buttons. Right now we are doing it in the sort of hackish way in contact us component and modal content component - it would be great to standarzie this issue.

**Comment by w1stler** [comment]
Sugmit? :>

**Comment by OtisRed** [comment]
@OtisRed evaluate this

**Comment by OtisRed** [comment]
Instead of moving this id into global class we could create theme according to vuetify documentation: https://vuetifyjs.com/en/customization/theme

**Comment by MargoWM** [comment]
closed for now
@Loczi94 we gave up the idea
