### ISSUE TITLE
Remove "message" / "msg" from endpoints

### ISSUE THREAD

**Issue by w1stler** [CodeForPoznan/codeforpoznan.pl_v3#215]
... unless it's a really meaningful & custom error message.

**Comment by OtisRed** [comment]
@3SpaceJT

**Comment by OtisRed** [comment]
@halsing you takeover that ticket @3SpaceJT when you come back we'll find you some other task to do

**Comment by OtisRed** [comment]
I closed it because @stanislawK had an issue with this issue for a long time and it does not make sense to dwell on it till it comes up again.
