### ISSUE TITLE
Define license for the project

### ISSUE THREAD

**Issue by OtisRed** [CodeForPoznan/codeforpoznan.pl_v3#225]
Discuss and choose which copyleft license we want to have in this project

**Comment by MargoWM** [comment]
MIT vs CC by4 ?

**Comment by MargoWM** [comment]
6:2 for MIT

**Comment by magul** [comment]
CC-By-4 usually applies to non-code assets. In the coding realm, we tend to MIT.

**Comment by monikakrawczak** [comment]
@OtisRed
