### ISSUE TITLE
Repair padding in social media component

### ISSUE THREAD

**Issue by OtisRed** [CodeForPoznan/codeforpoznan.pl_v3#246]
![Zrzut ekranu z 2020-02-26 21-14-30](https://user-images.githubusercontent.com/28675024/75383764-419c4b00-58dd-11ea-85c5-5be8337bd6fb.png)

Below the buttons (within the bottom pudding) there is a white line that shoudln't be there.

Probably the problem is that the white space is margin, not padding that would take the color from the higher element

**Comment by Loczi94** [comment]
Done in #264
