### ISSUE TITLE
Fix the bug in the hour and place

### ISSUE THREAD

**Issue by MargoWM** [CodeForPoznan/codeforpoznan.pl_v3#251]
![image.png](https://images.zenhubusercontent.com/5dc310adbe940c0001fed847/eb946332-e999-425e-a18f-d8d40652f175)

**Comment by OtisRed** [comment]
Should be "18:00" and "Mostowa 38 niedaleko Pawilonu w parku Stare Koryto Warty"

**Comment by agata-m** [comment]
@agata-m taken! ;)
