### ISSUE TITLE
Overlaping packages @mdi/font

### ISSUE THREAD

**Issue by OtisRed** [CodeForPoznan/codeforpoznan.pl_v3#266]
Do we need the same package in both these places? I'm not sure what's thetechnical difference between dependencies and devDependencies in this case. 

**Warning from terminal, while running docker-compose:**
warning package.json: "dependencies" has dependency "@mdi/font" with range "^4.5.95" that collides with a dependency in "devDependencies" of the same name with version "^4.7.95"
warning frontend@0.1.0: "dependencies" has dependency "@mdi/font" with range "^4.5.95" that collides with a dependency in "devDependencies" of the same name with version "^4.7.95"

**Comment by magul** [comment]
It shouldn't be defined in both places. Basically:
> "dependencies": Packages required by your application in production.
"devDependencies": Packages that are only needed for local development and testing.

see: https://docs.npmjs.com/specifying-dependencies-and-devdependencies-in-a-package-json-file
