### ISSUE TITLE
Add/edit project members 

### ISSUE THREAD

**Issue by MargoWM** [CodeForPoznan/codeforpoznan.pl_v3#303]
#### General description
In order to assign people to projects we created `team.py` that is not handled in any way on the frontend. 

#### Current behavior
We cannot add users to teams.

#### Expected behavior
Similar to hacknight list solution

#### Design
Our UX team currently works on the landing page. Therefore at the moment we have to figure out for ourselves how it may look like and where it should be placed. At the moment I suggest creating something that is similar to existing components on the dashboard and placing it there until we figure out how the user flow should look like.

**Comment by OtisRed** [comment]
Waiting for the proposal for general design of the backoffice

**Comment by OtisRed** [comment]
I close it because dividing the function of creating and editing that form seems redundant
