### ISSUE TITLE
Redirection for unspecified routes

### ISSUE THREAD

**Issue by stanislawK** [CodeForPoznan/codeforpoznan.pl_v3#318]
#### Subject of the issue:
When user tries to enter path which is not specified in router blank page is displayed

#### Your environment:
* version/branch
* which browser and its version

#### Steps to reproduce:
Navigate to https://dev.codeforpoznan.pl/test 

#### Actual behaviour:
User is able to access any path with blank page displayed, and what is worse also /api paths in dev env.

#### Expected behaviour:
User is able to access only routes which are specified in router, another paths should be redirected to home page "/"

#### Technical suggestion
You can define catchAll function similar to this:
![image](https://user-images.githubusercontent.com/28675024/97044712-c591fa00-1574-11eb-83d5-ec526bc00385.png)

**Comment by OtisRed** [comment]
Two questions. 
1. Is this case regards only outside user or also logged_in user? In other words, do guards for logged_in user prevent that problem in case of the logged_in user? 
1. Do you have any suggestion regarding solution?
