### ISSUE TITLE
Add public calendar on the website

### ISSUE THREAD

**Issue by magul** [CodeForPoznan/codeforpoznan.pl_v3#321]
#### Subject
We deliverered publicly available calendar of Code for Poznań events (see for reference: https://github.com/CodeForPoznan/Community/issues/80). It would be great to have that some how exposed on our website.

#### To-do list
- [ ] Embed google calendar on the join-us component
- [ ] Style the calendar to fit the current design

#### Resources
https://www.youtube.com/watch?v=vksO63XQQ3w

#### Calendar address
https://calendar.google.com/calendar/u/0/embed?src=hello@codeforpoznan.pl&ctz=Europe/Warsaw

**Comment by OtisRed** [comment]
A little bit about customization option to change the appearance:
https://www.youtube.com/watch?v=vksO63XQQ3w

**Comment by OtisRed** [comment]
UX
1. UX matter: yes
1. Kind of input: kind of information it contains (e.g. naming events), if its necessary, the way it is displayed
1. Prioryty: medium

**Comment by OtisRed** [comment]
@Gasimli

**Comment by OtisRed** [comment]
@Gasimli you coud try to fit calendar view in "join us" component - semantically it makes sense to show when we meet next to the information how to join us

**Comment by OtisRed** [comment]
Given the relative complexity of this problem and UX concerns regarding implementation I close it for now
