### ISSUE TITLE
500 when unique constraint fails for edit participant

### ISSUE THREAD

**Issue by stanislawK** [CodeForPoznan/codeforpoznan.pl_v3#328]
#### Subject of the issue:
When we try to edit participant with id=1, and assign to him/her email (or any other unique field) which is assigned to another user already (e.g. edit participant1 with email from participant2), we are getting 500 and [Error response](https://app.zenhub.com/files/156603153/cb09d1e4-91e9-45a2-9e68-2c22fcc55202/download) in html

#### Your environment:
* master

#### Steps to reproduce:
PUT http://localhost:5000/api/participants/2/ with:
```
{
    "email": <paste another user email>
}
```

#### Actual behaviour:
500 status code with html response

#### Expected behaviour:
400 with descriptive error message in json format

**Comment by w1stler** [comment]
Closing
