### ISSUE TITLE
Remove participant from hacknight

### ISSUE THREAD

**Issue by stanislawK** [CodeForPoznan/codeforpoznan.pl_v3#369]
#### Subject of the issue:
User should be able to remove participant from hacknight

#### Actual behaviour:
User can add new participants to hacknight, but once added participant can not be removed

#### Expected behaviour:
Some button should be visible next to each participant on the list in order to easily remove one from hacknight if necessary
![participants_list.png](https://images.zenhubusercontent.com/5b58955341d21c44472aef99/cb4e4ad8-d483-4fc9-9457-8763a45a9b5e)

**Comment by OtisRed** [comment]
This is the subject of #364 so I close it at this point :)
