### ISSUE TITLE
Create new participant form - adjust back-end validation

### ISSUE THREAD

**Issue by Marce1ina** [CodeForPoznan/codeforpoznan.pl_v3#379]
#### Subject of the issue:
After changes in validation on front-end [#309](https://github.com/CodeForPoznan/codeforpoznan.pl_v3/issues/309), back-end validation for 'Slack nick' and 'GitHub Username' needs to be adjusted as follows:
- 'Github username' should accept **latin alphabet letters**, as well as **numbers** and **-**, with the constraint that username cannot start or end with **-**,
- 'Slack nick' should accept **latin alphabet letters**, as well as **polish diacritical characters (żźćńółęąś)**, **numbers** and **,.';-_/()[]{}**. 

#### Actual behaviour:
On form submit, characters accepted by front-end are rejected by back-end.

#### Resources
It's possibly enough to copy regex from `frontend/src/helpers/validation.js` to `backend/serializers/participant_serializer.py`.

**Comment by Marce1ina** [comment]
@OtisRed this shouldn't block https://github.com/CodeForPoznan/codeforpoznan.pl_v3/issues/376. It could block https://github.com/CodeForPoznan/codeforpoznan.pl_v3/issues/309 - but doesn't have to.

**Comment by stanislawK** [comment]
PR has been submitted.
