### ISSUE TITLE
Website content - spelling, style corrections etc.

### ISSUE THREAD

**Issue by KSodowska** [CodeForPoznan/codeforpoznan.pl_v3#396]
#### Subject of the issue:
@OtisRed  I've corrected some of the mistakes/styling on the website, feel free to change/comment. If it's ok, part "Should be" is ready to copy-paste.

**Now:**
Kim jesteśmy?
Grupą osób, która uważa, że warto ulepszać świat za pomocą technologii i chce dostarczać narzędzia, _dzięki którym każdy będzie mógł to robić._ 

**Should be:**
Kim jesteśmy?
Grupą osób, która uważa, że warto ulepszać świat za pomocą technologii i chce dostarczać narzędzia, _które każdy będzie mógł w tym celu wykorzystać._ 

**Now:**
Co robimy?
Projektujemy. Programujemy. Testujemy. Poprawiamy. Tworzymy aplikacje społeczne, które aktywują użytkowników do działania na rzecz swojej społeczności czy jakiegoś interesu społecznego. 

**Should be:**
Co robimy?
Projektujemy. Programujemy. Testujemy. Poprawiamy. Tworzymy aplikacje społeczne, które aktywują użytkowników do działania na rzecz swojej społeczności, interesu społecznego oraz wspierają codzienną pracę wolontariuszy. Tworzymy aplikacje użyteczne :)

**Comment by KSodowska** [comment]
**Volontulo**

**Now:**
Portal Volontulo powstał dla ludzi i organizacji skupionych wokół idei pomocy innym poprzez udział we wolontariacie. Celem projektu jest pomoc we wzajemnym odnalezieniu się ludzi, którzy chcą realizować się jako wolontariusze/szki oraz organizacji i instytucji, które takich osób poszukują. Podział na strefę "Wolontariusza" oraz "Strefę organizacji i instytucji" umożliwa użytkownikom zwinną nawigację na stronie.

**Should be:**
Portal Volontulo powstał dla ludzi i organizacji skupionych wokół idei pomocy innym poprzez udział w wolontariacie. Celem projektu jest pomoc we wzajemnym odnalezieniu się ludzi, którzy chcą realizować się jako wolontariusze/wolontariuszki oraz organizacji i instytucji, które takich osób poszukują. Podział na strefę "Wolontariusza" oraz "Strefę organizacji i instytucji", umożliwia użytkownikom intuicyjne i sprawne poruszanie się po stronie.

**Comment by KSodowska** [comment]
PAH Fleet Manager

**Now:**
W wyniku współpracy z Polską Akcją Humanitarną stworzyliśmy aplikację pomagającą w logistycznych procesach akcji humanitarnych w różnych częściach globu. Aktualnie aplikacja służąca rejestracji i ewidencji przejazdów jest wykorzystywana podczas akcji humanitarnych na Ukrainie, w Sudanie Południowym, Jemenie oraz Somalii. Aplikacja pozwala także na eksport zebranych danych w celu ewidencji kosztów dla danej akcji humanitarnej. Dzięku temu możemy zoptymalizować proces i zmniejszyć nakład papierkowej pracy biurowej.

**Should be:**
W wyniku współpracy z Polską Akcją Humanitarną, stworzyliśmy aplikację wspierającą zarządzanie logistyką akcji humanitarnych w różnych częściach globu. Aktualnie aplikacja służąca rejestracji i ewidencji przejazdów jest wykorzystywana podczas akcji humanitarnych na Ukrainie, w Sudanie Południowym, Jemenie oraz Somalii. Aplikacja pozwala także na eksport zebranych danych, w celu ewidencji kosztów dla danej akcji humanitarnej. Dzięki temu, możemy zoptymalizować proces i znacząco zmniejszyć ilość czasu poświęconego na wypełnianie potrzebnej dokumentacji.

**Comment by KSodowska** [comment]
Alinka

Now:
Aplikacja Alinka powstała w celu optymalizacji codziennej pracy w poradniach psychologiczno-pedagogicznych. Jako byli pracownicy takiej poradni doskonale rozumiemy jakiego nakładu pracy wymaga wydanie orzeczenia czy sporządzenie protokołu z posiedzenia komisji. Aplikacja Alinka jest odpowiedzią na trudności, z jakimi spotykają się w codziennej pracy pracownicy administracji poradni. Nazwa aplikacji: „Alinka” to imię prawdziwej osoby, która musi wykonywać tę nudną, ale bardzo ważną pracę. Mamy nadzieję, że któregoś dnia ta aplikacja pomoże w jej pracy :).

Should be:
Aplikacja Alinka powstała w celu optymalizacji codziennej pracy w poradniach psychologiczno-pedagogicznych. Jako byli pracownicy takiej poradni, doskonale rozumiemy jakiego nakładu pracy wymaga wydanie orzeczenia, czy sporządzenie protokołu z posiedzenia komisji. Aplikacja Alinka jest odpowiedzią na trudności, z którymi borykają się w codziennej pracy pracownicy administracji poradni. Nazwa aplikacji, „Alinka”, to imię rzeczywistej osoby, która musi wykonywać tę nudną, ale bardzo ważną pracę. Mamy nadzieję, że któregoś dnia ta aplikacja pomoże jej w pracy :)

**Comment by KSodowska** [comment]
**Bank Empatii**

**Now:**
Bank Empatii to projekt strony Patrycji Krawczyk, która zmaga się z białaczką limfoblastyczną i chce znaleźć dawcę komórek macierzystach o podobnym do Patrycji kodzie genetycznym. Trzy główne panele "Historia Patrycji", "Jak wygląda badanie? oraz "Gdzie się zgłosić?" kierują użytkowników strony do uzyskania informacji na temat jak zostać dawcą szpiku oraz czym jest Rejestr Dawców. Na stronie znajduje się mapa Polski z umiejscowieniem punktów poboru krwi.

**Should be:**
Bank Empatii to projekt strony Patrycji Krawczyk, która zmaga się z białaczką limfoblastyczną. Ma na celu znalezienie dawcy komórek macierzystych o kodzie genetycznym podobnym do Patrycji. Trzy główne panele: "Historia Patrycji", "Jak wygląda badanie? oraz "Gdzie się zgłosić?", kierują użytkowników strony do uzyskania informacji na temat jak zostać dawcą szpiku oraz czym jest Rejestr Dawców. Na stronie znajduje się mapa Polski, z umiejscowieniem punktów poboru krwi.

**Comment by KSodowska** [comment]
**StreetMix**

**Now:** 
Oryginalny Streetmix jest dziełem Code for America, które w 2013 roku podczas hacknightu postanowiło stworzyć narzędzie, które pomoże miejskim planistom w przedstawianiu koncepcji ich planu na rewitalizacje miejskiej przestrzeni. Najczęstszym rozwiązaniem po jakie sięgają planiści jest wykonanie makiet z papieru, które zwizualizują krajobraz. Tworząc internetową wersję tego działania, planiści mogą dotrzeć do szerszego grona odbiorców niż podczas samych spotkań, a także pozwolić członkom społeczności na dzielenie się i remiksowanie swoich dzieł. Jest to jeden z pierwszych naszych projektów, które mieliśmy przyjemność przetłumaczyć tak, aby można było wykorzystać te rozwiązanie na polskim gruncie.

**Shoud be:**
Oryginalny Streetmix jest dziełem Code for America, które podczas hacknightu w 2013 roku, postanowiło stworzyć narzędzie wspierające miejskich planistów w przedstawianiu koncepcji ich planu na rewitalizację miejskiej przestrzeni. Najczęstszym rozwiązaniem po jakie sięgają planiści, jest wykonanie makiet z papieru, które zwizualizują krajobraz. Tworząc internetową wersję tego działania, planiści mogą dotrzeć do szerszego grona odbiorców niż podczas samych spotkań, a także pozwolić członkom społeczności na dzielenie się i remiksowanie swoich dzieł. Jest to jeden z pierwszych naszych projektów, które mieliśmy przyjemność przetłumaczyć tak, aby można było wykorzystać go na polskim gruncie.

**Comment by KSodowska** [comment]
Strona społeczności

Now:
Jest to trzecia wersja strony internetowej naszej organizacji. To pokazuje, że jako stowarzyszenie ciągle się rozwijamy i potrzebujemy nowych narzędzi i funkcjonalności do codziennej pracy. Aktualna forma strony jest wynikiem ponad 3 lat działalności jako Code for Poznań.

Shoud be:
Jest to trzecia wersja strony internetowej naszej organizacji. To pokazuje, że jako stowarzyszenie ciągle się rozwijamy i potrzebujemy nowych narzędzi oraz funkcjonalności do codziennej pracy. Aktualna forma strony jest wynikiem ponad 3 lat działalności, jako Code for Poznań.

**Comment by OtisRed** [comment]
Regarding the section descriptions we are working on it here: 
https://docs.google.com/document/d/14whlZfEuUAThAu5QAy-BoanLtSDR7-o1S9ZAUrG_wx4/edit?ts=60a531df

As soon as we are finished we will refresh all the content according to the suggestions made
