### ISSUE TITLE
Project title 'Strona społeczności' doesn't adjust to the miniature width.

### ISSUE THREAD

**Issue by KSodowska** [CodeForPoznan/codeforpoznan.pl_v3#402]
#### Subject of the issue:
In the projects part on the website, title 'Strona społeczności' doesn't display properly in it's miniature, it cuts off the last letter when zoom is 100% and the screen size is as mentioned above. This issue shows up on a certain conditions and doesn't reproduce on Windows 10 and MacOS (due to cross-website testing, but also @Marce1ina checked it out herself on MacOs). 
This problem doesn't show up on the master. 

#### Your environment:
* #376 
* Webrowser: Firefox 88.0, Chrome 90.0 (Ubuntu)
* Screen: 1366x768, 1360x768
* Zoom: 100% (works fine when it's 90% and less,110% or more)

#### Steps to reproduce:

1. Go to http://localhost:8080/#projects
2. Set your zoom to 100%.

#### Actual behaviour:
'Strona społeczności' title doesn't adjust properly to the miniature width, it cuts off the last letter.

#### Expected behaviour:
'Strona społeczności' title should adjust its size to the miniature width.

#### Attachments
![issue_376](https://user-images.githubusercontent.com/78560011/118361416-acda4780-b58b-11eb-98c8-e766977e81b3.gif)

**Comment by OtisRed** [comment]
Indeed there is a moment on the viewport scale between 1264 and 1266px where the name is too long and a letter jumps to another line. We should use css to break the title (break-word property maybe?)
