### ISSUE TITLE
Add missing hacknights to DB

### ISSUE THREAD

**Issue by OtisRed** [CodeForPoznan/codeforpoznan.pl_v3#416]
#### Subject of the issue:
I wanted to make belated attendance lists but we have no option yet to generate hacknights retrospectively (I added a task for that)

#### Technical suggestion
Please follow the list below to the letter because in Feb and March there were some hacknights added but not consistently. Given our past experience with sqlAlchemy and overlapping ids after pushing participants by hand I would be wary for a similar overlap here.

#### Missing hacknights
2021-02-10
2021-02-24
2021-03-03
2021-03-10
2021-03-24
2021-03-31
2021-04-07
2021-04-14
2021-04-21
2021-04-28
2021-05-05
2021-05-12
2021-05-19
2021-05-26
2021-06-02
2021-06-09

**Comment by w1stler** [comment]
Done on dev. ;-)

**Comment by w1stler** [comment]
```insert
    into
    hacknight (date)
values(
    ('2021-02-10'),
    ('2021-02-24'),
    ('2021-03-03'),
    ('2021-03-10'),
    ('2021-03-24'),
    ('2021-03-31'),
    ('2021-04-07'),
    ('2021-04-14'),
    ('2021-04-21'),
    ('2021-04-28'),
    ('2021-05-05'),
    ('2021-05-12'),
    ('2021-05-19'),
    ('2021-05-26'),
    ('2021-06-02'),
    ('2021-06-09')
);```
