### ISSUE TITLE
Remove Travis build status from readme.md and add Github Action's one

### ISSUE THREAD

**Issue by w1stler** [CodeForPoznan/codeforpoznan.pl_v3#503]
#### Subject of the issue:
Remove Travis build status from readme.md. Add Github Actions badge.

#### Your environment:
-

#### Steps to reproduce:
Go to readme.md page and observe first line.

#### Actual behaviour:
Error is visible

#### Expected behaviour:
No badge is displayed from travis, but the one from Github Actions

**Comment by Gasimli** [comment]
Should it be like this? [![deploy to staging](https://github.com/CodeForPoznan/codeforpoznan.pl_v3/actions/workflows/deploy-staging.yml/badge.svg)](https://github.com/CodeForPoznan/codeforpoznan.pl_v3/actions/workflows/deploy-staging.yml) because I don't see "Build" option in workflows section

**Comment by w1stler** [comment]
We've got two deploy jobs, so I'd just add the staging one (as I would assume that prod should be always working ;-)).
