### ISSUE TITLE
Create component to Add participants to hacknight

### ISSUE THREAD

**Issue by OtisRed** [CodeForPoznan/codeforpoznan.pl_v3#55]
Multi-select dropdown widget with save button (disable Enter key on save button).

![slim-select](https://user-images.githubusercontent.com/1165138/61813823-fe5d9380-ae46-11e9-9e5e-d1b5d19d8fad.png)

**Comment by w1stler** [comment]
First approach:
- separate views (URLs) for adding participants to hacknight and viewing participatns for particular hacknight (`hacknights/id`)

Second approach:
- above - list of participants
- below - multi-select dropdown as a separate section with Save & Cancel button
- Save buttons appends the participants to the list

**Comment by OtisRed** [comment]
![IMG_20190724_200451](https://user-images.githubusercontent.com/28675024/61907414-b2d1e500-af2d-11e9-9133-8540c29c3997.jpg)
