### ISSUE TITLE
Teams

### ISSUE THREAD

**Issue by OtisRed** [CodeForPoznan/codeforpoznan.pl_v3#58]
#### General description
We decided to add a team class, which could inform us which person belongs to which team. This information might be useful to get the colleagues from the project better as well as managing that team (e.g. rendering the latest attendance for the members of the team). This epic will contain any task that have anything to do with this.

**Comment by w1stler** [comment]
- assign participants to teams (Alinka team, CfP team)
- create other tickets - serializers, db models, etc.

**Comment by OtisRed** [comment]
We have too many epics and this is to specific at this moment. I close it not to multpliy the general aims
