### ISSUE TITLE
Upgrade Python to 3.7.3

### ISSUE THREAD

**Issue by w1stler** [CodeForPoznan/codeforpoznan.pl_v3#68]

**Comment by w1stler** [comment]
I might try to do it along with black. Should we upgrade to 3.8 @magul ?

**Comment by magul** [comment]
The black introduction is in #74 . We should do it separately. Also, as we don't have a production environment, we can choose whatever we want, but as we will run it on AWS Lambda, we should probably stick to whatever is available there: https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html

**Comment by magul** [comment]
Ok, I've just seen #187 so part of my comment here out of date.
