### ISSUE TITLE
Find a CC0 license image of magnifier glass

### ISSUE THREAD

**Issue by OtisRed** [CodeForPoznan/codeforpoznan.pl_v3#97]
In the assets directory (introduced in #88) there is an image of magnifier glass that is rendered when you hover the mouse over the project image. 

This image comes from wikipedia and is licensed with CC BY 3.0 which means that in order to use it we have to credit the author in some visible place which is aesthetically troublesome for a landing page.

Therefore we need a similar image that is licensed for the public unlimited use (licences as CC0 or MIT), that we could deploy instead.

Steps to do:
1) Find an image of magnifying glass, which can be used based on CC0, MIT or similar license
2) Switch the images in the assets/images/ directory
3) Remember to change the image reference in ourProjects

**Comment by Tomasz1234** [comment]
I will do it

**Comment by magul** [comment]
Done in #245
